<?php

use Livewire\Component;
use App\Models\Project;
use Illuminate\Support\Facades\Auth;
use Livewire\Attributes\Computed;

new class extends Component {
    #[Computed]
    public function projects()
    {
        /**
          Fuckass query to get the projects the models are generated from reliese package
          Still learning the foreign key relationships generated by reliese package
        **/

        $projects = Project::whereHas('members', function ($query) {
            $query->where('user_email', Auth::user()->email);
        })->where('status', 'active')->with('members.user')->withCount('members')->get();

        return $projects;
    }

};
?>

<div>
    {{-- Projects Grid --}}
    <div class="row g-4" wire:poll.5s.visible>
        @forelse($this->projects as $project)
            <div class="col-12 col-sm-6 col-xl-4">
                <div class="card h-100 rounded-4 border-0 shadow-sm project-card"
                    style="cursor:pointer; transition: transform .18s, box-shadow .18s;">

                    <div class="rounded-top-4 d-flex align-items-center gap-3 px-4 py-4 position-relative overflow-hidden"
                        style="background: linear-gradient(135deg, {{ $project->color }} 0%, {{ $project->color }}cc 50%, {{ $project->color }}88 100%); min-height: 110px;">
                        {{-- Project Colour --}}

                        {{-- Decorative ellipses --}}
                        <div
                            style="position:absolute;top:-20px;right:-10px;width:90px;height:90px;border-radius:50%;background:rgba(255,255,255,.12);pointer-events:none;">
                        </div>
                        <div
                            style="position:absolute;bottom:-40px;left:20%;width:120px;height:120px;border-radius:50%;background:rgba(255,255,255,.06);pointer-events:none;">
                        </div>

                        <div class="flex-shrink-0 rounded-3 overflow-hidden"
                            style="width:52px; height:52px; box-shadow: 0 2px 8px rgba(0,0,0,.18);">
                            @if($project->icon)
                                <img src="{{ Storage::url($project->icon) }}" width="52" height="52" {{-- Project Icon --}}
                                    alt="Project icon" style="width:100%; height:100%; object-fit:cover;">
                            @else
                                <div class="board-icon"
                                    style="background-color: grey; display:flex; align-items:center; justify-content:center; color:#fff; font-weight:700; font-size:1.2rem; width: 52px; height: 52px;">
                                    {{ strtoupper(substr($project->name, 0, 1)) }}
                                </div>
                            @endif
                        </div>

                        <div class="overflow-hidden flex-grow-1">
                            <h5 class="fw-bold text-white m-0 text-truncate">{{ $project->name }}</h5>{{-- Project Name --}}
                            <span class="badge rounded-pill text-white mt-1"
                                style="background:rgba(255,255,255,.2); font-size:.7rem;">
                            </span>
                        </div>
                    </div>

                    <div class="card-body px-4 pt-4 pb-3 d-flex flex-column">
                        <p class="text-muted small mb-4 flex-grow-1" style="line-height:1.6; min-height: 3em;">
                            {{ $project->description }} {{-- Project Description --}}
                        </p>

                        <div class="d-flex gap-3 mb-3">
                            <div class="d-flex align-items-center gap-1 text-muted small">
                                <i class="bi bi-people"></i>
                                <span>{{ $project->members_count }} Members</span> {{-- Member Count --}}
                            </div>
                            <div class="d-flex align-items-center gap-1 text-muted small">
                                <i class="bi bi-check2-square"></i>
                                <span>12 Tasks</span> {{-- Task Count --}}
                            </div>
                        </div>
                    </div>

                    {{-- Project Members --}}
                    <div
                        class="card-footer bg-transparent border-top-0 px-4 pb-4 pt-0 d-flex align-items-center justify-content-between">

                        <div class="d-flex align-items-center">
                            @foreach($project->members->take(5) as $index => $member)
                                @php
                                    $user = $member->user;
                                    $avatarUrl = empty($user->avatar)
                                        ? 'https://ui-avatars.com/api/?name=' . urlencode($user->name ?? 'User') . '&background=6366f1&color=fff'
                                        : (str_starts_with($user->avatar, 'http') ? $user->avatar : Storage::url($user->avatar));
                                @endphp
                                <div class="rounded-circle border border-2 border-white overflow-hidden"
                                    style="width:32px;height:32px;margin-right:-10px;z-index:{{ 5 - $index }};box-shadow:0 1px 4px rgba(0,0,0,.15);"
                                    title="{{ $user->name ?? 'User' }}">
                                    <img src="{{ $avatarUrl }}" width="32" height="32" alt="{{ $user->name ?? 'User' }}">
                                </div>
                            @endforeach
                            @if($project->members_count > 5)
                                <div class="rounded-circle border border-2 border-white d-flex align-items-center justify-content-center bg-secondary text-white"
                                    style="width:32px;height:32px;z-index:0;font-size:.65rem;font-weight:700;box-shadow:0 1px 4px rgba(0,0,0,.15);">
                                    +{{ $project->members_count - 5 }}
                                </div>
                            @endif
                        </div>
                        <div class="d-flex align-items-center gap-2">
                            {{-- Edit button --}}
                            @if($project->members->firstWhere('user_email', Auth::user()->email)?->role === 'owner')
                                <button type="button" class="btn btn-sm d-flex align-items-center justify-content-center"
                                    data-bs-toggle="modal" data-bs-target="#editProjectModal"
                                    data-project-id="{{ $project->id }}" data-project-name="{{ $project->name }}"
                                    data-project-description="{{ $project->description }}"
                                    data-project-color="{{ $project->color ?? '#6c63ff' }}"
                                    data-project-icon="{{ $project->icon ? Storage::url($project->icon) : '' }}"
                                    style="width: 32px; height: 32px; padding: 0; border-radius: 50%; background: transparent; color: #6c757d; transition: all 0.2s; border: 1px solid transparent;"
                                    onmouseover="this.style.background='rgba(108, 99, 255, 0.1)'; this.style.color='#6c63ff';"
                                    onmouseout="this.style.background='transparent'; this.style.color='#6c757d';"
                                    title="Edit project" onclick="event.stopPropagation()">
                                    <i class="bi bi-pencil" style="font-size: .85rem;"></i>
                                </button>
                            @endif

                            <a class="btn btn-sm rounded-pill px-3 btn-primary"
                                href="{{ route('project.board', $project->hashed_id) }}">
                                Board <i class="bi bi-kanban"></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        @empty
            <div class="col-12 text-center py-5 text-muted">
                <i class="bi bi-briefcase fs-1"></i>
                <p class="mt-3">You don't have any projects yet.</p>
            </div>
        @endforelse

    </div>

    <style>
        .project-card:hover {
            transform: translateY(-4px);
            box-shadow: 0 12px 28px rgba(108, 99, 255, .18) !important;
        }
    </style>
</div>